name: Deploy to Deno Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.2.4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: ${{ runner.os }}-deno-

      - name: Build site
        run: deno task build

      - name: Copy server.js to output directory
        run: cp server.js ./out/www/

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vietnguyen"
          entrypoint: "server.js"
          root: "./out/www"